name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git
        uses: actions/checkout@v3
        
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
       
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build & push server
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: gerrome/pern-store-app_server:1
          

      - name: Build & push client
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: gerrome/pern-store-app_client:1.4

      - name: Build & push client
        uses: docker/build-push-action@v3
        with:
          context: ./postgres
          push: true
          tags: gerrome/pern-store-app_postgres:1                  

      - name: Build & push nginx
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          push: true
          tags: gerrome/pern-store-app_nginx:1                  
